# ansible_user: ec2-user
# ansible_password: DevOps321

# MONGODB_HOST: mongodb-dev.mreddy.online
# redis: redis-dev.mreddy.online
# mysql: mysql-dev.mreddy.online
# rabbitmq: rabbitmq-dev.mreddy.online
# catalogue: catalogue.backend_alb_listener_arn-dev.mreddy.online
# user: user.backend_alb_sg_id-dev.mreddy.online
# cart: cart.backend-alb-dev.mreddy.online
# shipping: shipping.backend-alb-dev.mreddy.online
# payment: payment.backend-alb-dev.mreddy.online
# frontend: frontend-dev.mreddy.online
# catalogue: catalogue.backend-alb-dev.mreddy.online


ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-{{ env }}.daws88s.online
redis: redis-{{ env }}.daws88s.online
mysql: mysql-{{ env }}.daws88s.online
rabbitmq: rabbitmq-{{ env }}.daws88s.online
catalogue: catalogue.backend-alb-{{ env }}.daws88s.online
user: user.backend-alb-{{ env }}.daws88s.online
cart: cart.backend-alb-{{ env }}.daws88s.online
shipping: shipping.backend-alb-{{ env }}.daws88s.online
payment: payment.backend-alb-{{ env }}.daws88s.online
app_version: v3