ansible_user: ec2-user
ansible_password: DevOps321

MONGODB_HOST: mongodb-dev.mreddy.online
redis: redis-dev.mreddy.online
user: user.backend-alb-dev.mreddy.online
cart: cart.backend-alb-dev.mreddy.online
mysql: mysql.backend-alb-dev.mreddy.online
shipping: shipping.backend-alb-dev.mreddy.online
rabbitmq: rabbitmq-dev.mreddy.online
payment: payment.backend-alb-dev.mreddy.online
frontend: frontend-dev.mreddy.online
catalogue: catalogue.backend-alb-dev.mreddy.online